In [1]:
import nfl_data_py as nfl, pandas as pd, os

In [2]:
df = pd.read_parquet('2023_pbp.parquet') #pass 
df.query("play_type=='pass'")[['pass_touchdown','play_type','air_yards','yards_after_catch','yards_gained','touchdown','receiver_player_id','receiver_player_name','passer']].groupby(['passer','receiver_player_name']).count().reset_index()

,passer,receiver_player_name,pass_touchdown,play_type,air_yards,yards_after_catch,yards_gained,touchdown,receiver_player_id
0,A.Dalton,A.Thielen,14,14,14,11,14,14,14
1,A.Dalton,C.Hubbard,3,3,3,2,3,3,3
2,A.Dalton,D.Chark,11,11,11,4,11,11,11
3,A.Dalton,H.Hurst,3,3,3,1,3,3,3
4,A.Dalton,I.Thomas,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...
371,Z.Wilson,G.Wilson,22,22,22,12,22,22,22
372,Z.Wilson,M.Hardman,1,1,1,1,1,1,1
373,Z.Wilson,Mi.Carter,5,5,5,4,5,5,5
374,Z.Wilson,R.Cobb,4,4,4,1,4,4,4
375,Z.Wilson,T.Conklin,12,12,12,9,12,12,12

In [3]:
df.query("play_type=='pass'")[['passer', 'receiver_player_name']].groupby(['passer', 'receiver_player_name']).size().reset_index()

       passer receiver_player_name  count
0    A.Dalton            A.Thielen     14
1    A.Dalton            C.Hubbard      3
2    A.Dalton              D.Chark     11
3    A.Dalton              H.Hurst      3
4    A.Dalton             I.Thomas      1
..        ...                  ...    ...
371  Z.Wilson             G.Wilson     22
372  Z.Wilson            M.Hardman      1
373  Z.Wilson            Mi.Carter      5
374  Z.Wilson               R.Cobb      4
375  Z.Wilson            T.Conklin     12

[376 rows x 3 columns]

In [13]:
df_pass_td = df.query("play_type=='pass'")[['passer', 'receiver_player_name', 'pass_touchdown']].groupby(['passer', 'receiver_player_name']).sum().reset_index()
df_pass_td['total_pass'] = df.query("play_type=='pass'")[['passer', 'receiver_player_name']].groupby(['passer', 'receiver_player_name']).size().reset_index(name='total')[['total']]
df_pass_td['td_to_total_ratio'] = df_pass_td['pass_touchdown']/df_pass_td['total_pass']
df_pass_td

       passer receiver_player_name  pass_touchdown
0    A.Dalton            A.Thielen             1.0
1    A.Dalton            C.Hubbard             0.0
2    A.Dalton              D.Chark             1.0
3    A.Dalton              H.Hurst             0.0
4    A.Dalton             I.Thomas             0.0
..        ...                  ...             ...
371  Z.Wilson             G.Wilson             2.0
372  Z.Wilson            M.Hardman             0.0
373  Z.Wilson            Mi.Carter             0.0
374  Z.Wilson               R.Cobb             0.0
375  Z.Wilson            T.Conklin             0.0

[376 rows x 3 columns]