In [1]:
import nfl_data_py as nfl, pandas as pd

In [8]:
for x in [2021,2022,2023]:
    print("getting data for {}",str(x))
    data = nfl.import_pbp_data([x], downcast=True, alt_path=None)
    data.to_parquet("{}_pbp.parquet".format(str(x)))

getting data for {} 2021
2021 done.
Downcasting floats.
getting data for {} 2022
2022 done.
Downcasting floats.
getting data for {} 2023
2023 done.
Downcasting floats.

lets try to calculate average yards thrown per touchdown metric
play+type = pass, run

In [21]:
df_2022['interception'].unique()

array([ 0.,  1., nan], dtype=float32)

In [20]:
df_2022 = pd.read_parquet('2023_pbp.parquet')
df_2022 = df_2022[df_2022['passer'].notnull()]
df_2022[[
    'passer','touchdown','pass_touchdown','rush_touchdown','play_type','yards_gained','air_yards','yards_after_catch','interception'
]]

,passer,touchdown,pass_touchdown,rush_touchdown,play_type,yards_gained,air_yards,yards_after_catch,interception
3,S.Howell,0.0,0.0,0.0,pass,6.0,6.0,0.0,0.0
5,S.Howell,0.0,0.0,0.0,pass,0.0,10.0,NaN,0.0
6,S.Howell,0.0,0.0,0.0,pass,12.0,12.0,0.0,0.0
7,S.Howell,0.0,0.0,0.0,pass,1.0,-4.0,5.0,0.0
8,S.Howell,0.0,0.0,0.0,pass,0.0,3.0,NaN,0.0
...,...,...,...,...,...,...,...,...,...
8702,J.Goff,0.0,0.0,0.0,pass,-10.0,NaN,NaN,0.0
8705,J.Love,0.0,0.0,0.0,pass,-9.0,NaN,NaN,0.0
8706,J.Love,0.0,0.0,0.0,pass,12.0,9.0,3.0,0.0
8707,J.Love,0.0,0.0,0.0,pass,0.0,13.0,NaN,0.0
8716,J.Goff,0.0,0.0,0.0,pass,5.0,5.0,0.0,0.0

In [27]:
df_grouped = df_2022.groupby('passer')['yards_gained'].sum()
df_grouped = df_grouped[df_grouped > 100]
df_grouped

passer
A.Dalton         344.0
A.Richardson     287.0
B.Mayfield       650.0
B.Purdy          730.0
B.Young          322.0
C.Stroud         846.0
D.Carr           570.0
D.Jones          575.0
D.Prescott       661.0
D.Ridder         489.0
D.Watson         662.0
G.Minshew II     362.0
G.Smith          707.0
J.Allen          782.0
J.Burrow         530.0
J.Dobbs          543.0
J.Fields         528.0
J.Garoppolo      705.0
J.Goff          1013.0
J.Herbert        907.0
J.Hurts          630.0
J.Love           906.0
K.Cousins       1033.0
K.Pickett        640.0
L.Jackson        692.0
M.Jones          748.0
M.Stafford       885.0
P.Mahomes        904.0
R.Tannehill      454.0
R.Wilson         776.0
S.Howell         589.0
T.Lawrence       766.0
T.Tagovailoa    1030.0
Z.Wilson         454.0
Name: yards_gained, dtype: float32

In [28]:
df_grouped_td = df_2022.groupby('passer')['touchdown'].sum()
df_grouped_td = df_grouped_td[df_grouped_td > 0]
df_grouped_td

passer
A.Dalton        2.0
A.Richardson    1.0
B.Mayfield      4.0
B.Purdy         4.0
B.Young         2.0
C.Stroud        4.0
D.Carr          2.0
D.Jones         3.0
D.Prescott      3.0
D.Ridder        2.0
D.Watson        6.0
G.Minshew II    2.0
G.Smith         4.0
J.Allen         6.0
J.Burrow        2.0
J.Dobbs         3.0
J.Fields        6.0
J.Garoppolo     5.0
J.Goff          7.0
J.Herbert       6.0
J.Hurts         3.0
J.Love          8.0
K.Allen         1.0
K.Cousins       9.0
K.Pickett       4.0
L.Jackson       2.0
M.Jones         6.0
M.Stafford      2.0
M.White         1.0
P.Mahomes       8.0
R.Tannehill     1.0
R.Wilson        6.0
S.Howell        6.0
T.Lawrence      4.0
T.Tagovailoa    8.0
Z.Wilson        2.0
Name: touchdown, dtype: float32

In [31]:
df_ratio = df_grouped_td.merge(df_grouped, on='passer')
df_ratio['yards_per_touchdown'] = df_ratio['yards_gained'] / df_ratio['touchdown']
df_ratio = df_ratio.sort_values('yards_per_touchdown')
df_ratio

              touchdown  yards_gained  yards_per_touchdown
passer
J.Fields            6.0         528.0            88.000000
S.Howell            6.0         589.0            98.166664
D.Watson            6.0         662.0           110.333336
P.Mahomes           8.0         904.0           113.000000
J.Love              8.0         906.0           113.250000
K.Cousins           9.0        1033.0           114.777779
M.Jones             6.0         748.0           124.666664
T.Tagovailoa        8.0        1030.0           128.750000
R.Wilson            6.0         776.0           129.333328
J.Allen             6.0         782.0           130.333328
J.Garoppolo         5.0         705.0           141.000000
J.Goff              7.0        1013.0           144.714279
J.Herbert           6.0         907.0           151.166672
K.Pickett           4.0         640.0           160.000000
B.Young             2.0         322.0           161.000000
B.Mayfield          4.0         650.0           162.500000
A.Dalton            2.0         344.0           172.000000
G.Smith             4.0         707.0           176.750000
G.Minshew II        2.0         362.0           181.000000
J.Dobbs             3.0         543.0           181.000000
B.Purdy             4.0         730.0           182.500000
T.Lawrence          4.0         766.0           191.500000
D.Jones             3.0         575.0           191.666672
J.Hurts             3.0         630.0           210.000000
C.Stroud            4.0         846.0           211.500000
D.Prescott          3.0         661.0           220.333328
Z.Wilson            2.0         454.0           227.000000
D.Ridder            2.0         489.0           244.500000
J.Burrow            2.0         530.0           265.000000
D.Carr              2.0         570.0           285.000000
A.Richardson        1.0         287.0           287.000000
L.Jackson           2.0         692.0           346.000000
M.Stafford          2.0         885.0           442.500000
R.Tannehill         1.0         454.0           454.000000

In [12]:
for x in nfl.see_pbp_cols():
    print(x)

play_id
game_id
old_game_id
home_team
away_team
season_type
week
posteam
posteam_type
defteam
side_of_field
yardline_100
game_date
quarter_seconds_remaining
half_seconds_remaining
game_seconds_remaining
game_half
quarter_end
drive
sp
qtr
down
goal_to_go
time
yrdln
ydstogo
ydsnet
desc
play_type
yards_gained
shotgun
no_huddle
qb_dropback
qb_kneel
qb_spike
qb_scramble
pass_length
pass_location
air_yards
yards_after_catch
run_location
run_gap
field_goal_result
kick_distance
extra_point_result
two_point_conv_result
home_timeouts_remaining
away_timeouts_remaining
timeout
timeout_team
td_team
td_player_name
td_player_id
posteam_timeouts_remaining
defteam_timeouts_remaining
total_home_score
total_away_score
posteam_score
defteam_score
score_differential
posteam_score_post
defteam_score_post
score_differential_post
no_score_prob
opp_fg_prob
opp_safety_prob
opp_td_prob
fg_prob
safety_prob
td_prob
extra_point_prob
two_point_conversion_prob
ep
epa
total_home_epa
total_away_epa
total_home_rush_epa
total_away_rush_epa
total_home_pass_epa
total_away_pass_epa
air_epa
yac_epa
comp_air_epa
comp_yac_epa
total_home_comp_air_epa
total_away_comp_air_epa
total_home_comp_yac_epa
total_away_comp_yac_epa
total_home_raw_air_epa
total_away_raw_air_epa
total_home_raw_yac_epa
total_away_raw_yac_epa
wp
def_wp
home_wp
away_wp
wpa
vegas_wpa
vegas_home_wpa
home_wp_post
away_wp_post
vegas_wp
vegas_home_wp
total_home_rush_wpa
total_away_rush_wpa
total_home_pass_wpa
total_away_pass_wpa
air_wpa
yac_wpa
comp_air_wpa
comp_yac_wpa
total_home_comp_air_wpa
total_away_comp_air_wpa
total_home_comp_yac_wpa
total_away_comp_yac_wpa
total_home_raw_air_wpa
total_away_raw_air_wpa
total_home_raw_yac_wpa
total_away_raw_yac_wpa
punt_blocked
first_down_rush
first_down_pass
first_down_penalty
third_down_converted
third_down_failed
fourth_down_converted
fourth_down_failed
incomplete_pass
touchback
interception
punt_inside_twenty
punt_in_endzone
punt_out_of_bounds
punt_downed
punt_fair_catch
kickoff_inside_twenty
kickoff_in_endzone
kickoff_out_of_bounds
kickoff_downed
kickoff_fair_catch
fumble_forced
fumble_not_forced
fumble_out_of_bounds
solo_tackle
safety
penalty
tackled_for_loss
fumble_lost
own_kickoff_recovery
own_kickoff_recovery_td
qb_hit
rush_attempt
pass_attempt
sack
touchdown
pass_touchdown
rush_touchdown
return_touchdown
extra_point_attempt
two_point_attempt
field_goal_attempt
kickoff_attempt
punt_attempt
fumble
complete_pass
assist_tackle
lateral_reception
lateral_rush
lateral_return
lateral_recovery
passer_player_id
passer_player_name
passing_yards
receiver_player_id
receiver_player_name
receiving_yards
rusher_player_id
rusher_player_name
rushing_yards
lateral_receiver_player_id
lateral_receiver_player_name
lateral_receiving_yards
lateral_rusher_player_id
lateral_rusher_player_name
lateral_rushing_yards
lateral_sack_player_id
lateral_sack_player_name
interception_player_id
interception_player_name
lateral_interception_player_id
lateral_interception_player_name
punt_returner_player_id
punt_returner_player_name
lateral_punt_returner_player_id
lateral_punt_returner_player_name
kickoff_returner_player_name
kickoff_returner_player_id
lateral_kickoff_returner_player_id
lateral_kickoff_returner_player_name
punter_player_id
punter_player_name
kicker_player_name
kicker_player_id
own_kickoff_recovery_player_id
own_kickoff_recovery_player_name
blocked_player_id
blocked_player_name
tackle_for_loss_1_player_id
tackle_for_loss_1_player_name
tackle_for_loss_2_player_id
tackle_for_loss_2_player_name
qb_hit_1_player_id
qb_hit_1_player_name
qb_hit_2_player_id
qb_hit_2_player_name
forced_fumble_player_1_team
forced_fumble_player_1_player_id
forced_fumble_player_1_player_name
forced_fumble_player_2_team
forced_fumble_player_2_player_id
forced_fumble_player_2_player_name
solo_tackle_1_team
solo_tackle_2_team
solo_tackle_1_player_id
solo_tackle_2_player_id
solo_tackle_1_player_name
solo_tackle_2_player_name
assist_tackle_1_player_id
assist_tackle_1_player_name
assist_tackle_1_team
assist_tackle_2_player_id
assist_tackle_2_player_name
assist_tackle_2_team
assist_tackle_3_player_id
assist_tackle_3_player_name
assist_tackle_3_team
assist_tackle_4_player_id
assist_tackle_4_player_name
assist_tackle_4_team
tackle_with_assist
tackle_with_assist_1_player_id
tackle_with_assist_1_player_name
tackle_with_assist_1_team
tackle_with_assist_2_player_id
tackle_with_assist_2_player_name
tackle_with_assist_2_team
pass_defense_1_player_id
pass_defense_1_player_name
pass_defense_2_player_id
pass_defense_2_player_name
fumbled_1_team
fumbled_1_player_id
fumbled_1_player_name
fumbled_2_player_id
fumbled_2_player_name
fumbled_2_team
fumble_recovery_1_team
fumble_recovery_1_yards
fumble_recovery_1_player_id
fumble_recovery_1_player_name
fumble_recovery_2_team
fumble_recovery_2_yards
fumble_recovery_2_player_id
fumble_recovery_2_player_name
sack_player_id
sack_player_name
half_sack_1_player_id
half_sack_1_player_name
half_sack_2_player_id
half_sack_2_player_name
return_team
return_yards
penalty_team
penalty_player_id
penalty_player_name
penalty_yards
replay_or_challenge
replay_or_challenge_result
penalty_type
defensive_two_point_attempt
defensive_two_point_conv
defensive_extra_point_attempt
defensive_extra_point_conv
safety_player_name
safety_player_id
season
cp
cpoe
series
series_success
series_result
order_sequence
start_time
time_of_day
stadium
weather
nfl_api_id
play_clock
play_deleted
play_type_nfl
special_teams_play
st_play_type
end_clock_time
end_yard_line
fixed_drive
fixed_drive_result
drive_real_start_time
drive_play_count
drive_time_of_possession
drive_first_downs
drive_inside20
drive_ended_with_score
drive_quarter_start
drive_quarter_end
drive_yards_penalized
drive_start_transition
drive_end_transition
drive_game_clock_start
drive_game_clock_end
drive_start_yard_line
drive_end_yard_line
drive_play_id_started
drive_play_id_ended
away_score
home_score
location
result
total
spread_line
total_line
div_game
roof
surface
temp
wind
home_coach
away_coach
stadium_id
game_stadium
aborted_play
success
passer
passer_jersey_number
rusher
rusher_jersey_number
receiver
receiver_jersey_number
pass
rush
first_down
special
play
passer_id
rusher_id
receiver_id
name
jersey_number
id
fantasy_player_name
fantasy_player_id
fantasy
fantasy_id
out_of_bounds
home_opening_kickoff
qb_epa
xyac_epa
xyac_mean_yardage
xyac_median_yardage
xyac_success
xyac_fd
xpass
pass_oe